# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "testing"
client_id = "6d36d2b7795a71bc0e5e210d4291c554"
application_url = "https://moreover-vernon-expansys-consisting.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://moreover-vernon-expansys-consisting.trycloudflare.com/auth/callback",
  "https://moreover-vernon-expansys-consisting.trycloudflare.com/auth/shopify/callback",
  "https://moreover-vernon-expansys-consisting.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mmg-development-store.myshopify.com"
